version: '3.8'
services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  user:
    build:
      context: ./user-management
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    restart: always
    depends_on:
      - "mongodb"
    environment:
      - NODE_ENV=production

  messaging:
    build:
      context: ./messaging
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    depends_on:
      - "mongodb"
    environment:
      - NODE_ENV=production

volumes:
  mongo-data: